name: Push the Docker image to AWS ECR Repo

on: 
  workflow_dispatch:
    inputs:
      image-tag:
        required: true
        type: string

env:
  BASE_REPO: intellecta-lk/intellecta
   
jobs:
    Build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
           repository: ${{ env.BASE_REPO }}
           token: ${{secrets.PRIVATE_TOKEN}}
           ref: server-fix

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build, tag, and push the image to Amazon ECR
          id: build-image
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
            IMAGE_TAG: ${{ inputs.image-tag }}
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
